main/urls.py
from django.urls import path

from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('miscellaneous/', views.miscellaneous, name='miscellaneous'),
]

urlpatterns += staticfiles_urlpatterns()

story9/urls.py
from django.urls import path
from .views import *
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'story9'

urlpatterns = [
    path('', index, name='index'),
    path('register/', register_views, name='register'),
    path('login/', login_views, name='login'),
    path('logout/', logged_out, name='logout'),
    
]

urlpatterns += staticfiles_urlpatterns()

storyoxa/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('story1/', include('story1.urls')),
    path('matkul/', include('matkul.urls')),
    path('story6/', include('story6.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls')),
    path('story9/', include('story9.urls')),
]

story9/models.py
from django.db import models

# Create your models here.

story9/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CreateUser(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'password1',
            'password2',
        ]
        labels = {
            'first_name' : 'First name',
            'last_name' : 'Last name',
        }

story9/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from .forms import *

@login_required(login_url='story9:login')
def index(request):
    if request.method == 'POST':
        logout(request)
        return redirect('story9:logout')
    else:
        user = request.user
        context = {
            'user':user,
        }
        return render(request, 'story9/index.html', context)

def register_views(request):
    if request.method == 'POST':
        form = CreateUser(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('story9:index')
    form = CreateUser()
    context = {
        'form':form,
    }
    return render(request, 'story9/register.html', context)

def login_views(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('story9:index')
    
    form = AuthenticationForm()
    context = {
        'form':form,
    }
    return render(request, 'story9/login.html', context)

def logged_out(request):
    return render(request, 'story9/logout.html')

story9/templates/story9/index.html
{% extends 'base_vanilla.html' %}
{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'story9/css/style.css' %}" />

<title> Story 9 </title>
{% endblock meta %}

{% block content %}

<section class="wrapper">
    <div id="topend">
        <form method="POST">
            {% csrf_token %}
            <button id="logout-btn" type="submit">Logout</button>
        </form>
    </div>

    
    <div class="text-center">
        <h3 class="mtxt" id="greetings"> Hello {{ user.username }}! </h3>
        <hr class="mline">
    </div>
</section>

{% endblock content %}

story9/templates/story9/login.html
{% extends 'base_vanilla.html' %}
{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'story9/css/style.css' %}" />

<title> Login </title>
{% endblock meta %}

{% block content %}
<section class="wrapper">
    <h4>Log In</h4>
    <form class="app-form" method="post">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}">
        {% endif %}
        <br>
        <button type="submit" class="btn btn-success"> Log In </button>
    </form>
    <p>don't have an account yet? <a href="{% url 'story9:register' %}">register</a> </p> 
</section>
{% endblock content %}

story9/templates/story9/logout.html
{% extends 'base_vanilla.html' %}
{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'story9/css/style.css' %}" />

<title> Story 9 </title>
{% endblock meta %}

{% block content %}
<section class="wrapper">
    <div class="text-center">
        <h6 class="mtxt" id="logged-out-msg"> You have been successfully logged out </h6>
        <hr class="mline">
        <p><a href="{% url 'story9:login' %}"> log back in</a></p>
    </div>
    
</section>
{% endblock content %}

story9/templates/story9/register.html
{% extends 'base_vanilla.html' %}
{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'story9/css/style.css' %}" />

<title> Register </title>
{% endblock meta %}

{% block content %}
<section class="wrapper">
    <h4>Register</h4>
    <form class="app-form" method="post">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}">
        {% endif %}
        <br> <br>
        <button type="submit" class="btn btn-success"> Register </button>
    </form>
</section>
{% endblock content %}