main/urls.py
from django.urls import path

from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('miscellaneous/', views.miscellaneous, name='miscellaneous'),
]

urlpatterns += staticfiles_urlpatterns()

story6/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'story6'

urlpatterns = [
    path('', views.kegiatan, name='kegiatan'),
    path('create-kegiatan/', views.createKegiatan, name='form_kegiatan'),
    path('create-peserta/<int:id>', views.createPeserta, name='form_peserta'),
]

urlpatterns += staticfiles_urlpatterns()

storyoxa/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('story1/', include('story1.urls')),
    path('matkul/', include('matkul.urls')),
    path('story6/', include('story6.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls')),
    path('story9/', include('story9.urls')),
]

story6/models.py
from django.db import models

class Kegiatan(models.Model):
    nama = models.CharField(max_length=50)

    def __str__(self):
        return self.nama

class Peserta(models.Model):
    nama = models.CharField(max_length=50)
    Kegiatan = models.ForeignKey(Kegiatan, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.nama

story6/forms.py
from django import forms
from . import models

class CreateKegiatan(forms.ModelForm):
    class Meta:
        model = models.Kegiatan
        fields = ['nama']


class CreatePeserta(forms.ModelForm):
    class Meta:
        model = models.Peserta
        fields = ['nama']

story6/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import *
from . import forms


def kegiatan(request):
    list_kegiatan = Kegiatan.objects.all()
    list_peserta = Peserta.objects.all()
    context = {
        'list_kegiatan': list_kegiatan,
        'list_peserta': list_peserta,
    }
    return render(request, 'story6/index.html', context)

def createKegiatan(request):
    form = forms.CreateKegiatan()
    if request.method == 'POST':
        form = forms.CreateKegiatan(request.POST)

        if form.is_valid():
            form.save()
            return redirect('story6:kegiatan')
    
    return render(request, 'story6/form_kegiatan.html', {'form' : form})

def createPeserta(request, id):
    form = forms.CreatePeserta()
    if request.method == 'POST':
        print(request.POST)
        kegiatan = Kegiatan.objects.get(id=id)
        nama_peserta = request.POST.get('nama')
        Peserta.objects.create(Kegiatan=kegiatan, nama=nama_peserta)
        return redirect('story6:kegiatan')

    return render(request, 'story6/form_peserta.html', {'form' : form})

story6/templates/story6/form_kegiatan.html
{% extends 'base_vanilla.html' %}
{% load static %}

{% block meta %}
<title> Buat Kegiatan </title>
{% endblock meta %}

{% block content %}

<section class="lg-fbg">

    <h3>Buat Kegiatan:</h3>
    <hr>
    
    <form class="form-group" method="POST">
        {% csrf_token %}
        <table>{{form}}</table>
        <input type="submit" class="btn btn-success hehe" value="Daftar">
    </form>

    <a href="{% url 'story6:kegiatan' %}" class="btn btn-danger hehe">Cancel</a>

</section>

{% endblock content %}

story6/templates/story6/form_peserta.html
{% extends 'base_vanilla.html' %}
{% load static %}

{% block meta %}
<title> Daftar </title>
{% endblock meta %}

{% block content %}

<section class="lg-fbg">

    <h3>Daftar</h3>
    <hr>
    
    <form class="form-group" method="POST">
        {% csrf_token %}
        <table>{{form}}</table>
        <input type="submit" class="btn btn-success hehe" value="Daftar">
    </form>
    <a href="{% url 'story6:kegiatan' %}" class="btn btn-danger hehe">Cancel</a>

</section>

{% endblock content %}

story6/templates/story6/index.html
{% extends 'base_vanilla.html' %}
{% load static %}

{% block meta %}
<title> Story 6 </title>
{% endblock meta %}

{% block content %}

<section class="lg-fbg">

    <h2>Kegiatan</h2>
    <hr>

    {% for kegiatan in list_kegiatan %}
    <div class="card obj-kegiatan" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title">{{ kegiatan.nama }}</h5>
          <p class="card-text"> Peserta: </p>
        </div>
        
        <ul class="list-group list-group-flush">
        {% for peserta in list_peserta   %}
            {% if peserta.Kegiatan == kegiatan %}
                <li class="list-group-item">{{ peserta.nama }}</li>
            {% endif %} 
        {% endfor %}
        </ul>
        <div class="card-body">
            <a href="{% url 'story6:form_peserta' id=kegiatan.id %}" class="card-link">Daftar</a>
        </div>
      </div>
    {% endfor %}
    <a href="{% url 'story6:form_kegiatan' %}" class="btn btn-dark hehe">Tambah kegiatan</a>

</section>

{% endblock content %}