main/urls.py
from django.urls import path

from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('miscellaneous/', views.miscellaneous, name='miscellaneous'),
]

urlpatterns += staticfiles_urlpatterns()

matkul/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'matkul'

urlpatterns = [
    path('', views.matkul, name='matkul'),
    path('<slug:slug>', views.detail_matkul, name='detail'),
    path('create-matkul/', views.create_matkul, name='create_matkul'),
    path('delete/<int:id>', views.delete_matkul, name='delete_matkul'),
    path('update/<int:id>', views.update_matkul, name='update_matkul'),
]

urlpatterns += staticfiles_urlpatterns()

storyoxa/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('story1/', include('story1.urls')),
    path('matkul/', include('matkul.urls')),
    path('story6/', include('story6.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls')),
    path('story9/', include('story9.urls')),
]

matkul/models.py
from django.db import models
from django.utils.text import slugify

class Matkul(models.Model):
    nama = models.CharField(max_length=50)
    slug = models.SlugField(editable=False)
    dosen = models.CharField(max_length=50)
    sks = models.PositiveSmallIntegerField()
    deskripsi = models.TextField(max_length=500)
    sem_th = models.CharField(max_length=20)
    ruang = models.CharField(max_length=15)

    def __str__(self):
        return self.nama 
    
    def snippet(self):
        if len(self.deskripsi) > 35:
            return self.deskripsi[:35] + '...'
        else:
            return self.deskripsi
        

    def save(self):
        super(Matkul, self).save()
        self.slug = slugify(f'{self.id}-{self.nama}')
        return super(Matkul, self).save()

matkul/forms.py
from django import forms
from . import models

class CreateMatkul(forms.ModelForm):
    class Meta:
        model = models.Matkul
        fields = ['nama', 'dosen', 'sks', 'sem_th', 'ruang', 'deskripsi']
        

matkul/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Matkul
from . import forms


def matkul(request):
    list_matkul = Matkul.objects.all().order_by('nama')
    return render(request, 'matkul/index.html', {'list_matkul': list_matkul})

def detail_matkul(request, slug):
    matkul =  Matkul.objects.get(slug=slug)
    return render(request, 'matkul/details.html', {'matkul':matkul})

def create_matkul(request):
    form = forms.CreateMatkul()
    if request.method == 'POST':
        form = forms.CreateMatkul(request.POST)
        if form.is_valid():
            form.save()
            return redirect('matkul:matkul')    

    return render(request, 'matkul/create_matkul.html', {'form':form})

def update_matkul(request, id):
    matkul = Matkul.objects.get(id=id)
    form = forms.CreateMatkul(instance=matkul)
    if request.method == 'POST':
        form = forms.CreateMatkul(request.POST, instance=matkul)
        if form.is_valid():
            form.save()
            return redirect('matkul:matkul')

    return render(request, 'matkul/create_matkul.html', {'form':form})

def delete_matkul(request, id):
    Matkul.objects.get(id=id).delete()
    return redirect('matkul:matkul')

matkul/templates/matkul/create_matkul.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title> Tambah Matkul </title>
{% endblock meta %}

{% block content %}

<section class="lg-fbg">

    <h3>Form Mata Kuliah</h3>

    <form class="gen-form" action="" method="POST">
        {% csrf_token %}
        <table>{{form}}</table>
        <input type="submit" name="Tambahkan">
    </form>

</section>

{% endblock content %}

matkul/templates/matkul/details.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title> {{matkul.name}} </title>
{% endblock meta %}

{% block content %}

<section class="lg-fbg">

    <div class="matkul fluid-container">
        <h3>{{ matkul.nama }}</h3>
        <table>
            <tbody>
                <tr>
                    <td>Dosen</td>
                    <td> :    {{matkul.dosen}} </td>
                </tr>
                <tr>
                    <td>SKS </td>
                    <td> :    {{matkul.sks}} </td>
                </tr>
                <tr>
                    <td>Semester/Tahun</td>
                    <td> :    {{matkul.sem_th}} </td>
                </tr>
                <tr>
                    <td>Ruang kelas:</td>
                    <td> :    {{matkul.ruang}} </td>
                </tr>
            </tbody>
        </table>
        <br>
        <p>Deskripsi:</p> <br>
        <p> {{matkul.deskripsi}} </p> <br> <br>

        <a href="{% url 'matkul:update_matkul' matkul.id %}">Update</a> <br>
        <a href="{% url 'matkul:delete_matkul' matkul.id %}">Delete</a>

    </div>

</section>

{% endblock content %}

matkul/templates/matkul/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Matkul</title>
{% endblock meta %}

{% block content %}



<section class="lg-fbg">

    <h1 class="g-ttl-one">Mata Kuliah</h1>

    <hr class="f-hr">

    <div class="matkul fluid-container">
        {% for matkul in list_matkul %}
        <br>
        <h5> <a class="stn-text-g" href="{% url 'matkul:detail' slug=matkul.slug %}"> {{ matkul.nama }} </a> </h5>
        <br>
        {% endfor %}   
    </div>

    <a href="{% url 'matkul:create_matkul' %}">Tambahkan</a>

</section>



{% endblock content %}