main/urls.py
from django.urls import path

from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('miscellaneous/', views.miscellaneous, name='miscellaneous'),
]

urlpatterns += staticfiles_urlpatterns()

matkul/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'matkul'

urlpatterns = [
    path('', views.matkul, name='matkul'),
    path('<slug:slug>', views.detail_matkul, name='detail'),
    path('create-matkul/', views.create_matkul, name='create_matkul'),
    path('delete/<int:id>', views.delete_matkul, name='delete_matkul'),
    path('update/<int:id>', views.update_matkul, name='update_matkul'),
]

urlpatterns += staticfiles_urlpatterns()

story1/urls.py
from django.urls import path

from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'story1'

urlpatterns = [
    path('', views.story1, name='story1'),
]

urlpatterns += staticfiles_urlpatterns()

storyoxa/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('story1/', include('story1.urls')),
    path('matkul/', include('matkul.urls')),
    path('story6/', include('story6.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls')),
    path('story9/', include('story9.urls')),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href= "{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
<section id="nav-bar">
  <nav class="navbar navbar-expand-lg navbar-light">
      <a class="navbar-brand" href="{% url 'main:home' %}">Home</a>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'main:home' %}#about-me">About</a>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="{% url 'main:home' %}#contact-info">Contact</a>
            </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'main:miscellaneous' %}">Miscellaneous</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'story1:story1' %}">Story 1</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'matkul:matkul' %}">Mata Kuliah</a>
          </li>
        </ul>
      </div>
    </nav>
</section>
  {% block content %}
  {% endblock content %}

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

templates/base_vanilla.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href= "{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>

  {% block content %}
  {% endblock content %}

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>

</html>